### ISSUE TITLE
fflib_SObjectSelector: Entity is not api accessible on installation in prof. edition

### ISSUE THREAD

**Issue by mogenshoj** [financialforcedev/fflib-apex-common#110]
We recently upgraded fflib, and started seeing this error when installing on professional edition orgs (we have a managed package):

fflib_SObjectSelector: Entity is not api accessible on installation

We have not had any problems installing on enterprise edition orgs. Not sure why it happens, we fixed it by rolling back to an older version of the library.

**Comment by daveespo** [comment]
Sounds like #93 in different words

**Comment by mogenshoj** [comment]
Yes, it does sound like the same type of error.  

Just to clarify the issue we're seeing. We are not using a post install script as the other issue mentions, it just fails on installation. And only when installing in a professional edition org. (haven't tried in group edition). It works fine when installing in enterprise edition.

**Comment by afawcett** [comment]
Its most likely the RecordType reference [here](https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_SObjectSelector.cls#L40), since PE doesn't support them. Try removing this line from your deployment. I'll also turn this into an enhancement request to find a late bound way of checking implementing the check being performed in this class that will resolve this dependency.

**Comment by afawcett** [comment]
Thanks @tfuda for the fix to this, i love this community!
