### ISSUE TITLE
Auto Generate Selector classes

### ISSUE THREAD

**Issue by mohammedsaeed** [financialforcedev/fflib-apex-common#142]
Are there any tools auto-generate Selector classes for custom Salesforce data model?

**Comment by afawcett** [comment]
There are none no, that i am aware. In principle though, the idea is that its a human consideration based on what is known to be the common needs of the code base. It should not be all fields or some machine generated view of what fields are needed. This is the main reason why SOQL does not support "select * from myobject__c". Interested in your thoughts on this and use case behind your question?

**Comment by mohammedsaeed** [comment]
Was looking for a tool in which we can select objects, a list of fields per
object after which we get Selector classes generated for common functions
i.e. query (selective SOQL), pagination and DMLs.

**Comment by afawcett** [comment]
Oh i see, that would be a nice tool indeed! Makes sense now. Probably not something we would put in the repo though, so if its ok i'll close this discussion out. Thanks for sharing your idea though, hopefully you and/or others in the community will pick it up! 👍

**Comment by dlisovsky** [comment]
Please see the solution for easily [select all the fields](https://github.com/dlisovsky/apex-common/blob/master/src/classes/DynamicSelector.cls)

How to use:

1. [Inherit a class](https://github.com/dlisovsky/apex-common/blob/master/src/classes/UserSelector.cls)
2. Use an instance of DynamicSelector `new DynamicSelector(Contact.SObjectType).selectSobjectsById(ids) // select * from Contact where Id in :ids`

It also helps to generate a query factory with Parent/Child relationships:
`

        fflib_QueryFactory queryFactory = newQueryFactory();


        new DynamicSelector(Project_Task__c.sObjectType)
                .configureQueryFactoryFields(
                queryFactory,
                'Project_Task__c'
        );

        new DynamicSelector(Functional_Area__c.sObjectType)
                .configureQueryFactoryFields(
                queryFactory,
                'Project_Task__r.Functional_Area__c'
        );

        new DynamicSelector(Project__c.sObjectType)
                .configureQueryFactoryFields(
                queryFactory,
                'Project_Task__r.Functional_Area__r.Project__c'
        );

        new DynamicSelector(RecordType.getSObjectType())
                .configureQueryFactoryFields(
                queryFactory,
                'RecordType'
        );`

**Comment by afawcett** [comment]
Thanks for sharing @dlisovsky 

A few thoughts on this for your consideration...

- I would recommend you use only when the intent is you need ALL fields. My concerns if this is used generally is it will cause Apex heap governor issues. Since it will pull in a lot of data into memory, especially if an object has large text fields and you load a lot of records. The developer may not appreciate this from the name of your class or method, so just something to think about in terms of making more clear.

- By default the query factory created by the selector base class does not enabled field level security, so be sure to either enable this or check this in whatever client is displaying this data. 

- Related to my above point, adding all fields regardless of what business process or general usage dictates the fields needed, does add additional exposure to potentially sensitive data in the debug logs. The concern here is use of Subscriber Support login, where a debugging Partner dev can see more data than is granted to the user who approved Partner login can. That said, system / app code needs for certain data vs end user can attribute to this for valid reasons anyway. Just something to keep in mind.

Finally do have a careful think about what your motivations are for having ALL fields loaded.
