### ISSUE TITLE
fflib_SObjectSelectorTest failing due to CURRENCY_ISO_CODE_ENABLED

### ISSUE THREAD

**Issue by dudunato** [financialforcedev/fflib-apex-common#147]
Hey guys,

I got the following methods failing: testDefaultConfig, testGetFieldListString, testSOQL and testWithoutSorting. All of them have a statement to check if the currencyManagement is enable, if so, assert with one more field (CurrencyIsoCode).

The problem is with this method here:

```
System.debug('Currency -> ' +  fflib_SObjectDescribe.getDescribe(Account.SObjectType).getFieldsMap().keySet());
```

It returns all the keys in lowercase and we're expecting it in camel case:

```
private Boolean CURRENCY_ISO_CODE_ENABLED {
        get {
            if(CURRENCY_ISO_CODE_ENABLED == null){
                CURRENCY_ISO_CODE_ENABLED = describeWrapper.getFieldsMap().keySet().contains('CurrencyIsoCode');
            }
            return CURRENCY_ISO_CODE_ENABLED;
        }
		set;
    }
```

Is it a API version problem? 

Just to test it:

```
System.debug('Currency -> ' +  fflib_SObjectDescribe.getDescribe(Account.SObjectType).getFieldsMap().keySet().contains('currencyisocode'));
// return true

System.debug('Currency -> ' +  fflib_SObjectDescribe.getDescribe(Account.SObjectType).getFieldsMap().keySet().contains('CurrencyIsoCode'));
//return false
```

**Comment by frup42** [comment]
I think the correct logic should be
```
if(CURRENCY_ISO_CODE_ENABLED == null) {
    CURRENCY_ISO_CODE_ENABLED = describeWrapper.getFieldsMap().containsKey('CurrencyIsoCode');
    }
```

Turns out the fieldsMap is one of those Apex sleight of hands, where the keys are case insensitive - see https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_dynamic_field_tokens.htm for more info.

However, I can't replicate the test failures either - even after fiddling the API version of the fflib_SObjectDescribe and fflib_SObjectSelector classes. Closing for now, but let us know if you have more for us to go on.
