### ISSUE TITLE
Question: How and where does the fflib enforce FLS and CRUD permissions?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [financialforcedev/fflib-apex-common#160]
As describe in this Stackexchange question http://salesforce.stackexchange.com/questions/166368 the Checkmarx security scanner found several FLS and CRUD issues in my code but I was totally unable to simulate real FLS and CRUD problems. Triggers, pages and classes all seemed to magically enforce those admin-set permissions.

Can it be that the fflib is enforcing that. Where are using Domain classes and Selectors in their default forms.

**Comment by daveespo** [comment]
fflib can only enforce the "R" in CRUD and FLS as part of the core library. That is, it can only enforce the isAccessible() check on fields in the context of a Selector (ultimately down into QueryFactory). There's an overloaded constructor for fflib_SObjectSelector that lets you enforce CRUD and FLS

For DML (the "CUD" in CRUD), there's an interface you can implement in SObjectUnitOfWork called IDML. The purpose of this is to let you implement your own enforcement of CRUD and FLS. There's an overloaded constructor for fflib_SObjectUnitOfWork that lets you pass in an instance of your implementation.

We implemented DMLManager long ago (https://github.com/patronmanager/apex-dml-manager) and have gone through security review with several packages since then and it's been accepted as adequate protection. To bridge from SObjectUnitOfWork to DMLManager, you can write a light class that delegates the DML using the IDML interface like so:

````
public class SObjectUnitOfWorkDML implements fflib_SObjectUnitOfWork.IDML {
	public void dmlInsert(List<SObject> objList) { DMLManager.insertAsUser(objList); }
	public void dmlUpdate(List<SObject> objList) { DMLManager.updateAsUser(objList); }
	public void dmlDelete(List<SObject> objList) { DMLManager.deleteAsUser(objList); }
}
````

These two techniques (SObjectSelector that enforces CRUD and FLS) plus DMLManager should get you through security review.

As for how/why your existing code is behaving the way it is .. if they're Visualforce pages using `apex:inputField` and `apex:outputField`, those UI elements enforce CRUD/FLS automatically. As for any other behavior you're seeing ... it's well documented that Apex does not respect CRUD and FLS at all -- the only thing you can benefit from is `with sharing` where it enforces the sharing rules automatically. There's no equivalent for `apex:inputField` and `apex:outputField` in Lightning Components yet .. so you won't be able to get much more mileage out of automatic CRUD/FLS enforcement as VF becomes a legacy technology. 

While you're busy getting worked up over this, please vote this sucker up:

https://success.salesforce.com/ideaView?id=08730000000Lj8GAAS

**Comment by up2go-rsoesemann** [comment]
Thank you very much for this detailed answer.

**Comment by afawcett** [comment]
Thanks for sharing @daveespo, nice summary and great use of the UOW extensibility here, i just shared this on twitter as well. 👍 

DMLManager is a great library, but as you say it would better to have something more efficient and [platform based](https://success.salesforce.com/ideaView?id=08730000000Lj8GAAS) than re-querying the records to compare changes. I did [start a branch here](https://github.com/financialforcedev/fflib-apex-common/tree/fls-support-experiment) a while ago, recently updated to use the SObject.getPopulatedFieldsAsMap method (i need to retest it since a recent platform fix in this area).

**Comment by up2go-rsoesemann** [comment]
@afawcett I really would like to read a short blog post by you about how you use your own library to cope with security review's FLS and CRUD requirements. I mean having all those experiments and other libraries around still leaves me with the question if all of them are ready for production-time ;-)

**Comment by afawcett** [comment]
@up2go-rsoesemann Mostly by using the default checking, but overriding it when we want true system mode. These libraries do not of course avoid the need to do it in the client tier.

**Comment by cnaccio** [comment]
@daveespo Does your recommendation above still hold today, or have you come up with something more evolved? As @afawcett mentioned, I'm a bit concerned about the performance hit of requerying the data to figure out what's changed, but maybe I'm overthinking it. 

Any advice/feedback would be much appreciated. We're currently trying to get through security review, and are desperately attempting to come up with an elegant solution that isn't a nightmare to maintain long term.

Also, any advice on how to correctly ignore security when you have a valid use case would also be helpful. 

Thanks in advance!

**Comment by daveespo** [comment]
As of today (Spring '19), what I wrote in 2017 is still the 'state of the art'. We still use it and if you're looking for a low-complexity/low-impact way to honor CRUD and FLS, the performance hit is far outweighed by the engineering cost savings. 

We've never profiled the performance impact but since the records are retrieved using their IDs and it's bulkified, I'd be surprised if it's a hot spot worth optimizing. 

Having said all of that, Summer '19 contains a nugget that we've been waiting for patiently since it was introduced on a few talks during DF18.

https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_apex_Security_stripInaccessible.htm

We haven't actually mapped out the plan to retrofit the guts of DMLManager (https://github.com/patronmanager/apex-dml-manager) to use this method for honoring CRUD. One of the beauties of DMLManager's current implementation is that you can still perform an UPDATE on an existing SObject containing fields that the user doesn't have Edit access to -- as long as you're not trying to change the values on those fields. This is super convenient for the common case of retrieving a record for display, allowing the user to change a field or two (that they do have permission to change), then applying the update to the whole width of the retrieved record. 

`stripInaccessible` will only tell you if you're trying to persist an updated record that has fields populated that the user can't write to. That's subtly different.

**Comment by cnaccio** [comment]
Hey David, thanks so much for the response. We went ahead and implemented
DMLManager, with a slight modification for enforcing security on updates
within our triggers (Domain classes) since we were using the ff commons
library; felt like this gave us the best of both worlds.

Also, thanks for the heads up on stripInaccessible, this looks like it
could be very helpful.

Thanks again for putting together this library and helping another ISV make
it through security review :-)
Charles Naccio
*Founder*
p:(855) 550-0606
m:(214) 305-8684
w:www.billable.io

**Comment by cnaccio** [comment]
For those that come after me, here's the code from our security implementation which you can drop in if you're using the fflib commons library. Enjoy!

https://gist.github.com/cnaccio/4b1b44f49aa8cf4333a65aa9b3c32f23

**Comment by kristenjung** [comment]
I wonder if fflib and DMLManager have been passed the PMD test.
I can find many pmd violations on fflib and DMLManager. Was it acceptable by security review for ISV managed package.

**Comment by tfuda** [comment]
We use fflib-apex-commons (fflib_SObjectUnitOfWork, fflib_SObjectSelector, fflib_QueryFactory) and DMLManager in managed packages that have been through security review. They were approved as a solution for enforcing CRUD and FLS. The application code, including fflib-apex-commons and DMLManager were run through the Checkmarx static analysis tool as part of the security review process.

**Comment by rsoesemann** [comment]
@kristenjung as far as I can see PMD doesn’t find any security issues in the two libs but doesn’t like the complexity and code conventions of the code. If security review would look for that the appexchange would be mostly empty.

**Comment by kristenjung** [comment]
Thank you very much for reply!!
Have a nice day.
