### ISSUE TITLE
Can't use fflib_SObjectSelector classes at post-install time

### ISSUE THREAD

**Issue by tfuda** [financialforcedev/fflib-apex-common#93]
We've integrated a number of fflib classes into one of our managed packages. We are making extensive use of fflib_SObjectSelector within our application. We also utilize the capability where you can invoke an Apex class upon completion of package installation into subscriber orgs. We're trying to construct an instance of one of our custom SObjectSelector classes and use it to run queries at post-install time. What we're finding is that at post-install time, we're getting the following error:
```
There was a problem creating the Fee records
Entity is not api accessible
Stack trace:
Class.PatronTicket.fflib_SObjectSelector: line 35, column 1
Class.PatronTicket.SObjectSelector.<init>: line 15, column 1
Class.PatronTicket.Selector_FeeSlot.<init>: line 37, column 1
Class.PatronTicket.Service_Fee.createFeeSlotObjects: line 205, column 1
Class.PatronTicket.Service_Fee.configureUnitFeeSlot: line 373, column 1
Class.PatronTicket.PostInstallOperations.migrateFeesFromPTicketSettings: line 91, column 1
Class.PatronTicket.PostInstallOperations.doPostInstallOperations: line 33, column 1
Class.PatronTicket.PostInstallOperations.onInstall: line 12, column 1
Line number: 35
```

This can be traced back to the following static initialization code in fflib_SObjectSelector:
```
    /**
     * This overrides the Multi Currency handling, preventing it from injecting the CurrencyIsoCode fie ld for certain System objects that don't ever support it
     **/
    private static Set<String> STANDARD_WITHOUT_CURRENCYISO = new Set<String> { AsyncApexJob.SObjectType.getDescribe().getName()
                                                                                , ApexClass.SObjectType.getDescribe().getName()
                                                                                , Attachment.SObjectType.getDescribe().getName()
                                                                                , RecordType.SObjectType.getDescribe().getName() };
```

This same code executes just fine from application context, as well as unit test context. I suspect this is one of those quirky issues that only occurs when your code executes in the context of the post-install user. Has anyone else experienced this?

**Comment by tmowbrey** [comment]
You may want to view the recently updated fflib_SobjectSelector (pull 91 - https://github.com/financialforcedev/fflib-apex-common/pull/91).

RecordType.SObjectType.getDescribe().getName() needs to be updated to RecordType.getSObjectType().getDescribe().getName() and may be the source of your issue.

**Comment by tfuda** [comment]
Thank you. I will merge in the pull request and create a package and try it. There's no other way to verify whether it addresses my post-install problem other than creating a new package. Please vote for this idea if you have a moment: https://success.salesforce.com/ideaView?id=08730000000DpREAA0. If it works, I will report back here. Might be a few days.

**Comment by afawcett** [comment]
@tfuda yep we've hit this recently as well, we have a case out with Salesforce on it, be interested actually if the recent change does resolve it, let us know. And yep testing post install problems is not great. I've just upvoted your idea and will tweet.

**Comment by tfuda** [comment]
Sadly, I created a package today that included the code change from pull request #91. Unfortunately, I am still getting the same failure from my InstallHandler code when the static initializer for the STANDARD_WITHOUT_CURRENCYISO set is initialized. So, I believe this is still problematic for InstallHandler classes that wish to utilize fflib_SObjectSelector.

**Comment by afawcett** [comment]
Ok, i'll see if i can get an update on the fix related to this issue.

**Comment by cb-chaitanya** [comment]
@tfuda We've recently included the enterprise patterns into our managed package.When we used fflib_SObjectSelector in a class which is called by post install class, we're receiving the following error even though the user is System Administrator **DMLManager.CRUDException: Access Denied: OP_INSERT** .Is it because of the with sharing keyword on fflib_SObjectSelector class and Is it recommended to use fflib_SObjectSelector in post install context?

**Comment by daveespo** [comment]
@cb-chaitanya -- a few things:

 * DMLManager is not part of this project -- it's a separate library that is compatible with fflib-apex-common `fflib_SObjectUnitOfWork` but it has nothing to do with this thread (`fflib_SObjectSelector`) which is dealing with SOQL queries during package installation
 * Post-Install code runs as a ghost user -- this is "documented" over here: https://salesforce.stackexchange.com/questions/32607/installhandler-runs-under-a-special-ghost-user-what-rights-does-it-have -- in short, you need to both make sure your InstallHandler class is declared 'without sharing' and any DML you're doing needs to ignore CRUD and FLS

Lastly, be careful about any DML you do in an InstallHandler class. If you schedule Scheduled Apex or run Batch Apex, those async jobs will run as the ghost user and you'll find all sorts of strange permission problems that you have no way of troubleshooting since you can never impersonate that user. Plus, if you include the Last Modified By field for any records modified by the ghost user on a Report, the records will not appear because the running user will not have access to that ghost user's User record.

**Comment by cb-chaitanya** [comment]
@daveespo Thank you so much for your valuable information.We're planning to schedule a job on installation that does heavy DML intense job.But for now we'll explore different options to schedule this.
